# Site-wide generic info (overridable per-page)
title: ahoneycutt.me
description: Aaron Honeycutt's website
author: Aaron Honeycutt
theme-color: "#452981"
image: https://ahoneycutt.me/images/card.png

# Site-wide hardcoded (non-overridable by pages)
made-in: Colorado
birthday: '1992-12-31 00:08:00 -0600'

# Site-wide social info
donate: https://ahoneycutt.me/pay
email: aaronhoneycutt@pm.me
github_user: ahoneybun # user with no @
gravatar: a112b4952ec7f583808683b2b289d2be # Gravatar md5 hash
instagram: athoneycutt # user with no @
pixelfed: "https://pixelfed.social/ahoneybun" # whole URL since it's federated
mastodon: "https://mastodon.social/web/accounts/106886163803369357" # whole URL since it's federated
steam: ahoneybun # user/alias, no @
twitter: "@fishfulpenguin" # user including @

# Settings
permalink: /blog/:title/
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

collections:
  products:
    output: true
    permalink: /store/:path

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
