# Site-wide generic info (overridable per-page)
title: ahoneycutt.me
description: Aaron Honeycutt's website
author: Aaron Honeycutt
theme-color: "#452981"
image: https://ahoneycutt.me/images/card.png

# Site-wide hardcoded (non-overridable by pages)
made-in: Colorado
birthday: '1992-12-31 00:08:00 -0600'

# Site-wide social info
donate: https://ahoneycutt.me/pay
email: aaronhoneycutt@pm.me
github_user: ahoneycutt # user with no @
gravatar: 41275ecc8271aca852ce2c0ff72d2610 # Gravatar md5 hash
instagram:  # user with no @
mastodon: "https://fosstodon.org/web/accounts/194490" # whole URL since it's federated
steam: ahoneybunn # user/alias, no @
twitter: "@fishfulpenguin" # user including @

# Settings
permalink: /blog/:title/
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

collections:
  products:
    output: true
    permalink: /store/:path

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
